### ISSUE TITLE
Cannot delete pending jobs

### ISSUE THREAD

**Issue by lukemaxwell** [HyperionGray/starbelly#34]
A pending job that fails to run becomes 'stuck', with no option to delete. Attempting to delete via the API raises the following exception:

```
app_1  | 2020-06-23 12:52:49 [starbelly.server] ERROR: Exception while handling request:
app_1  | request_id: 0
app_1  | delete_job {
app_1  |   job_id: "\013M\212\315b\\E\337\241d;[[n\013\332"
app_1  | }
app_1  | Traceback (most recent call last):
app_1  |   File "/starbelly/starbelly/server/__init__.py", line 236, in _handle_request
app_1  |     await handler(*args)
app_1  |   File "/starbelly/starbelly/server/job.py", line 20, in delete_job
app_1  |     await server_db.delete_job(job_id)
app_1  |   File "/starbelly/starbelly/db.py", line 930, in delete_job
app_1  |     raise Exception('Can only delete cancelled or completed jobs.')
app_1  | Exception: Can only delete cancelled or completed jobs.
```

**Comment by lukemaxwell** [comment]
It's possible to delete this job using the API by first setting the status to cancelled, and thereafter sending the delete request.

This is not possible using the UI as the action buttons are not visible - this should be a different ticket.
