### ISSUE TITLE
Server exception when set_job fields empty

### ISSUE THREAD

**Issue by lukemaxwell** [HyperionGray/starbelly#35]
Sending an API `RequestSetJob` request with empty fields raises exception:

```app_1  | 2020-06-23 14:18:43 [starbelly.server] ERROR: Exception while handling request:
app_1  | request_id: 0
app_1  | set_job {
app_1  | }
app_1  | Traceback (most recent call last):
app_1  |   File "/starbelly/starbelly/server/__init__.py", line 236, in _handle_request
app_1  |     await handler(*args)
app_1  |   File "/starbelly/starbelly/server/job.py", line 156, in set_job
app_1  |     policy_id = str(UUID(bytes=command.policy_id))
app_1  |   File "/usr/lib/python3.7/uuid.py", line 169, in __init__
app_1  |     raise ValueError('bytes is not a 16-char string')
app_1  | ValueError: bytes is not a 16-char string
```

**Comment by lukemaxwell** [comment]
https://github.com/HyperionGray/starbelly/pull/37
